version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: yeoman-generator
    versions:
    - 4.12.0
    - 4.13.0
    - 5.0.1
    - 5.1.0
